package com.edwards.biz.itemMng;

import java.io.OutputStream;
import java.util.Map;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletResponse;

import org.apache.ibatis.session.ResultContext;
import org.apache.ibatis.session.ResultHandler;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.hssf.usermodel.HSSFDataFormat;
import org.apache.poi.xssf.streaming.*;
import org.apache.poi.xssf.usermodel.*;

public class SebItemExcel implements ResultHandler<Map<String,Object>> {
	private HttpServletResponse response;
	private SXSSFSheet sheet;
	private SXSSFWorkbook workbook;
	private boolean isStarted = false;

	XSSFCellStyle style   = null;
	XSSFCellStyle style1  = null;
	XSSFCellStyle style20 = null;
	XSSFCellStyle style22 = null;

	public SebItemExcel(HttpServletResponse response){
		this.response = response;
		workbook = new SXSSFWorkbook(100);
		sheet = workbook.createSheet("자재관리");
		sheet.setColumnWidth(0, 2000);
		sheet.setColumnWidth(1, 2500);
		sheet.setColumnWidth(2, 2500);
		sheet.setColumnWidth(3, 3000);
		sheet.setColumnWidth(4, 4000);
		sheet.setColumnWidth(5, 9000);
		sheet.setColumnWidth(6, 9000);
		sheet.setColumnWidth(7, 5000);
		sheet.setColumnWidth(8, 5000);
		sheet.setColumnWidth(9, 4000);
		sheet.setColumnWidth(10, 2500);
		sheet.setColumnWidth(11, 2500);
		sheet.setColumnWidth(12, 2500);
		sheet.setColumnWidth(13, 3500);
		sheet.setColumnWidth(14, 3500);
		sheet.setColumnWidth(15, 2500);
		sheet.setColumnWidth(16, 2500);
		sheet.setColumnWidth(17, 7000);
		sheet.setColumnWidth(18, 7000);
		sheet.setColumnWidth(19, 9000);
		sheet.setColumnWidth(20, 10000);
		sheet.setColumnWidth(21, 4000);
		sheet.setColumnWidth(22, 5000);
		sheet.setColumnWidth(23, 7000);
		sheet.setColumnWidth(24, 4000);
		sheet.setColumnWidth(25, 4000);
		sheet.setColumnWidth(26, 5000);
		sheet.setColumnWidth(27, 7000);
		sheet.setColumnWidth(28, 4000);
		sheet.setColumnWidth(29, 4000);
		sheet.setColumnWidth(30, 5000);
		sheet.setColumnWidth(31, 4000);
		sheet.setColumnWidth(32, 5000);
		sheet.setColumnWidth(33, 6000);
		sheet.setColumnWidth(34, 3000);
		sheet.setColumnWidth(35, 7000);
		sheet.setColumnWidth(36, 3000);
		sheet.setColumnWidth(37, 10000);
		sheet.setColumnWidth(38, 4000);
		sheet.setColumnWidth(39, 6000);
		sheet.setColumnWidth(40, 3000);
		sheet.setColumnWidth(41, 8000);
		sheet.setColumnWidth(42, 8000);
		sheet.setColumnWidth(43, 8000);
		sheet.setColumnWidth(44, 8000);
		sheet.setColumnWidth(45, 8000);
		sheet.setColumnWidth(46, 8000);
		sheet.setColumnWidth(47, 8000);
		sheet.setColumnWidth(48, 8000);
		sheet.setColumnWidth(49, 3000);
		sheet.setColumnWidth(50, 4000);
		sheet.setColumnWidth(51, 4000);
		sheet.setColumnWidth(52, 4000);
		sheet.setColumnWidth(53, 4000);
		sheet.setColumnWidth(54, 4000);
		sheet.setColumnWidth(55, 4000);
		sheet.setColumnWidth(56, 4000);
		sheet.setColumnWidth(57, 4000);
		sheet.setColumnWidth(58, 2500);
	}

	@Override
	public void handleResult(ResultContext<? extends Map<String, Object>> result){
		try {
			if(!isStarted){
        		style   = (XSSFCellStyle) workbook.createCellStyle();
        		style1  = (XSSFCellStyle) workbook.createCellStyle();
        		style20 = (XSSFCellStyle) workbook.createCellStyle();
        		style22 = (XSSFCellStyle) workbook.createCellStyle();

        		style.setBorderBottom(BorderStyle.THIN);
            	style.setBorderLeft(BorderStyle.THIN);
            	style.setBorderRight(BorderStyle.THIN);
            	style.setBorderTop(BorderStyle.THIN);
        		style.setAlignment(HorizontalAlignment.CENTER);

        		style1.setBorderBottom(BorderStyle.THIN);
            	style1.setBorderLeft(BorderStyle.THIN);
            	style1.setBorderRight(BorderStyle.THIN);
            	style1.setBorderTop(BorderStyle.THIN);

        		style20.setDataFormat(HSSFDataFormat.getBuiltinFormat("#,##0"));
        		style20.setBorderBottom(BorderStyle.THIN);
            	style20.setBorderLeft(BorderStyle.THIN);
            	style20.setBorderRight(BorderStyle.THIN);
            	style20.setBorderTop(BorderStyle.THIN);
        		style20.setAlignment(HorizontalAlignment.RIGHT);

        		style22.setDataFormat(HSSFDataFormat.getBuiltinFormat("#,##0.00"));
        		style22.setBorderBottom(BorderStyle.THIN);
        		style22.setBorderLeft(BorderStyle.THIN);
        		style22.setBorderRight(BorderStyle.THIN);
        		style22.setBorderTop(BorderStyle.THIN);
        		style22.setAlignment(HorizontalAlignment.RIGHT);

        		response.setHeader("Content-Disposition","attachment;filename=\""+URLEncoder.encode("ItemStatus.xlsx", "UTF-8")+"\"");
        		isStarted = true;
        		SXSSFRow row = sheet.createRow(0);
        		SXSSFCell cell = row.createCell(0);
        		cell.setCellValue("Status");
        		cell.setCellStyle(style);
        		cell = row.createCell(1);
        		cell.setCellValue("Status명");
        		cell.setCellStyle(style);
        		cell = row.createCell(2);
        		cell.setCellValue("등록일");
        		cell.setCellStyle(style);
        		cell = row.createCell(3);
        		cell.setCellValue("CMMF Code");
        		cell.setCellStyle(style);
        		cell = row.createCell(4);
        		cell.setCellValue("Commercial Code");
        		cell.setCellStyle(style);
        		cell = row.createCell(5);
        		cell.setCellValue("Item Description(KOR)");
        		cell.setCellStyle(style);
        		cell = row.createCell(6);
        		cell.setCellValue("Item Description(ENG)");
        		cell.setCellStyle(style);
        		cell = row.createCell(7);
        		cell.setCellValue("Family Level 1");
        		cell.setCellStyle(style);
        		cell = row.createCell(8);
        		cell.setCellValue("Family Level 2");
        		cell.setCellStyle(style);
        		cell = row.createCell(9);
        		cell.setCellValue("무역거래처");
        		cell.setCellStyle(style);
        		cell = row.createCell(10);
        		cell.setCellValue("결제통화");
        		cell.setCellStyle(style);
        		cell = row.createCell(11);
        		cell.setCellValue("수입단가");
        		cell.setCellStyle(style);
        		cell = row.createCell(12);
        		cell.setCellValue("Incoterms");
        		cell.setCellStyle(style);
        		cell = row.createCell(13);
        		cell.setCellValue("FTA");
        		cell.setCellStyle(style);
        		cell = row.createCell(14);
        		cell.setCellValue("HS Code");
        		cell.setCellStyle(style);
        		cell = row.createCell(15);
        		cell.setCellValue("세율");
        		cell.setCellStyle(style);
        		cell = row.createCell(16);
        		cell.setCellValue("원산지");
        		cell.setCellStyle(style);
        		cell = row.createCell(17);
        		cell.setCellValue("원산지 표기 방법");
        		cell.setCellStyle(style);
        		cell = row.createCell(18);
        		cell.setCellValue("원산지 표기 위치");
        		cell.setCellStyle(style);
        		cell = row.createCell(19);
        		cell.setCellValue("제조자");
        		cell.setCellStyle(style);
        		cell = row.createCell(20);
        		cell.setCellValue("제조자 주소");
        		cell.setCellStyle(style);
        		cell = row.createCell(21);
        		cell.setCellValue("(1) Basic Model");
        		cell.setCellStyle(style);
        		cell = row.createCell(22);
        		cell.setCellValue("(1) 인증번호");
        		cell.setCellStyle(style);
        		cell = row.createCell(23);
        		cell.setCellValue("(1) 정격");
        		cell.setCellStyle(style);
        		cell = row.createCell(24);
        		cell.setCellValue("(1) 인증기관");
        		cell.setCellStyle(style);
        		cell = row.createCell(25);
        		cell.setCellValue("(2) Basic Model");
        		cell.setCellStyle(style);
        		cell = row.createCell(26);
        		cell.setCellValue("(2) 인증번호");
        		cell.setCellStyle(style);
        		cell = row.createCell(27);
        		cell.setCellValue("(2) 정격");
        		cell.setCellStyle(style);
        		cell = row.createCell(28);
        		cell.setCellValue("(2) 인증기관");
        		cell.setCellStyle(style);
        		cell = row.createCell(29);
        		cell.setCellValue("(3) Basic Model");
        		cell.setCellStyle(style);
        		cell = row.createCell(30);
        		cell.setCellValue("(3) 인증번호");
        		cell.setCellStyle(style);
        		cell = row.createCell(31);
        		cell.setCellValue("(4) Basic Model");
        		cell.setCellStyle(style);
        		cell = row.createCell(32);
        		cell.setCellValue("(4) 인증번호");
        		cell.setCellStyle(style);
        		cell = row.createCell(33);
        		cell.setCellValue("ID no.");
        		cell.setCellStyle(style);
        		cell = row.createCell(34);
        		cell.setCellValue("최초정밀날짜");
        		cell.setCellStyle(style);
        		cell = row.createCell(35);
        		cell.setCellValue("접수번호");
        		cell.setCellStyle(style);
        		cell = row.createCell(36);
        		cell.setCellValue("검사 종류");
        		cell.setCellStyle(style);
        		cell = row.createCell(37);
        		cell.setCellValue("식품접촉재질");
        		cell.setCellStyle(style);
        		cell = row.createCell(38);
        		cell.setCellValue("제조자 코드");
        		cell.setCellStyle(style);
        		cell = row.createCell(39);
        		cell.setCellValue("비고");
        		cell.setCellStyle(style);
        		cell = row.createCell(40);
        		cell.setCellValue("결과등급");
        		cell.setCellStyle(style);
        		cell = row.createCell(41);
        		cell.setCellValue("(1) 복합재질 필름.시트류 (LDPE)");
        		cell.setCellStyle(style);
        		cell = row.createCell(42);
        		cell.setCellValue("(2) 발포합성수지 (EPS)");
        		cell.setCellStyle(style);
        		cell = row.createCell(43);
        		cell.setCellValue("(3) 발포합성수지 (EPE)");
        		cell.setCellStyle(style);
        		cell = row.createCell(44);
        		cell.setCellValue("(4) 합성수지 단일재질용기,트레이류 (PET)");
        		cell.setCellStyle(style);
        		cell = row.createCell(45);
        		cell.setCellValue("(5) 합성수지 단일재질용기,트레이류 (PP)");
        		cell.setCellStyle(style);
        		cell = row.createCell(46);
        		cell.setCellValue("(6) 합성수지 단일재질용기,트레이류 (PE)");
        		cell.setCellStyle(style);
        		cell = row.createCell(47);
        		cell.setCellValue("(7) 발포합성수지 복합재질");
        		cell.setCellStyle(style);
        		cell = row.createCell(48);
        		cell.setCellValue("(8) 제품 플라스틱무게 ");
        		cell.setCellStyle(style);
        		cell = row.createCell(49);
        		cell.setCellValue("최초 통관일");
        		cell.setCellStyle(style);
        		cell = row.createCell(50);
        		cell.setCellValue("EcoAS 제품코드");
        		cell.setCellStyle(style);
        		cell = row.createCell(51);
        		cell.setCellValue("EcoAS 등록일");
        		cell.setCellStyle(style);
        		cell = row.createCell(52);
        		cell.setCellValue("Net WT. (KG)");
        		cell.setCellStyle(style);
        		cell = row.createCell(53);
        		cell.setCellValue("RoHS Report");
        		cell.setCellStyle(style);
        		cell = row.createCell(54);
        		cell.setCellValue("RoHS Model");
        		cell.setCellStyle(style);
        		cell = row.createCell(55);
        		cell.setCellValue("실제제품 사이즈 (가로*세로*높이)");
        		cell.setCellStyle(style);
        		cell = row.createCell(56);
        		cell.setCellValue("무게");
        		cell.setCellStyle(style);
        		cell = row.createCell(57);
        		cell.setCellValue("용량");
        		cell.setCellStyle(style);
        		cell = row.createCell(58);
        		cell.setCellValue("파일유무");
        		cell.setCellStyle(style);
        	}

        	Map<String, Object> dataRow = result.getResultObject();
        	Row row = sheet.createRow(result.getResultCount());
        	Cell cell = null;
        	cell = row.createCell(0);
        	cell.setCellValue(dataRow.get("StatusNow")==null ? "" : dataRow.get("StatusNow").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(1);
        	cell.setCellValue(dataRow.get("StatusNm")==null ? "" : dataRow.get("StatusNm").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(2);
        	cell.setCellValue(dataRow.get("RegDtm1")==null ? "" : dataRow.get("RegDtm1").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(3);
        	cell.setCellValue(dataRow.get("Mmodel_code")==null ? "" : dataRow.get("Mmodel_code").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(4);
        	cell.setCellValue(dataRow.get("CommercialCode")==null ? "" : dataRow.get("CommercialCode").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(5);
        	cell.setCellValue(dataRow.get("DescriptionKr")==null ? "" : dataRow.get("DescriptionKr").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(6);
        	cell.setCellValue(dataRow.get("DescriptionEn")==null ? "" : dataRow.get("DescriptionEn").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(7);
        	cell.setCellValue(dataRow.get("FamilyLevel1")==null ? "" : dataRow.get("FamilyLevel1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(8);
        	cell.setCellValue(dataRow.get("FamilyLevel2")==null ? "" : dataRow.get("FamilyLevel2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(9);
        	cell.setCellValue(dataRow.get("OverseaCustomer")==null ? "" : dataRow.get("OverseaCustomer").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(10);
        	cell.setCellValue(dataRow.get("Currency")==null ? "" : dataRow.get("Currency").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(11);
        	cell.setCellValue(dataRow.get("Danga")==null ? "" : dataRow.get("Danga").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(12);
        	cell.setCellValue(dataRow.get("Incoterms")==null ? "" : dataRow.get("Incoterms").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(13);
        	cell.setCellValue(dataRow.get("Fta")==null ? "" : dataRow.get("Fta").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(14);
        	cell.setCellValue(dataRow.get("HsCode")==null ? "" : dataRow.get("HsCode").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(15);
        	cell.setCellValue(dataRow.get("Seyul")==null ? "" : dataRow.get("Seyul").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(16);
        	cell.setCellValue(dataRow.get("Wonsanji")==null ? "" : dataRow.get("Wonsanji").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(17);
        	cell.setCellValue(dataRow.get("WonMarkType")==null ? "" : dataRow.get("WonMarkType").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(18);
        	cell.setCellValue(dataRow.get("WonMarkLoc")==null ? "" : dataRow.get("WonMarkLoc").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(19);
        	cell.setCellValue(dataRow.get("Manufacturer")==null ? "" : dataRow.get("Manufacturer").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(20);
        	cell.setCellValue(dataRow.get("ManufacturerAddr")==null ? "" : dataRow.get("ManufacturerAddr").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(21);
        	cell.setCellValue(dataRow.get("ElecBasicModel1")==null ? "" : dataRow.get("ElecBasicModel1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(22);
        	cell.setCellValue(dataRow.get("ElecCertiNo1")==null ? "" : dataRow.get("ElecCertiNo1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(23);
        	cell.setCellValue(dataRow.get("ElecRating1")==null ? "" : dataRow.get("ElecRating1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(24);
        	cell.setCellValue(dataRow.get("ElecCertiDept1")==null ? "" : dataRow.get("ElecCertiDept1").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(25);
        	cell.setCellValue(dataRow.get("ElecBasicModel2")==null ? "" : dataRow.get("ElecBasicModel2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(26);
        	cell.setCellValue(dataRow.get("ElecCertiNo2")==null ? "" : dataRow.get("ElecCertiNo2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(27);
        	cell.setCellValue(dataRow.get("ElecRating2")==null ? "" : dataRow.get("ElecRating2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(28);
        	cell.setCellValue(dataRow.get("ElecCertiDept2")==null ? "" : dataRow.get("ElecCertiDept2").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(29);
        	cell.setCellValue(dataRow.get("RadioBasicModel1")==null ? "" : dataRow.get("RadioBasicModel1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(30);
        	cell.setCellValue(dataRow.get("RadioCertiNo1")==null ? "" : dataRow.get("RadioCertiNo1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(31);
        	cell.setCellValue(dataRow.get("RadioBasicModel2")==null ? "" : dataRow.get("RadioBasicModel2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(32);
        	cell.setCellValue(dataRow.get("RadioCertiNo2")==null ? "" : dataRow.get("RadioCertiNo2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(33);
        	cell.setCellValue(dataRow.get("IdNo")==null ? "" : dataRow.get("IdNo").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(34);
        	cell.setCellValue(dataRow.get("DetailDtm")==null ? "" : dataRow.get("DetailDtm").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(35);
        	cell.setCellValue(dataRow.get("ReceiptNo")==null ? "" : dataRow.get("ReceiptNo").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(36);
        	cell.setCellValue(dataRow.get("ExamType")==null ? "" : dataRow.get("ExamType").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(37);
        	cell.setCellValue(dataRow.get("MatarialType")==null ? "" : dataRow.get("MatarialType").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(38);
        	cell.setCellValue(dataRow.get("ManufacturerCode")==null ? "" : dataRow.get("ManufacturerCode").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(39);
        	cell.setCellValue(dataRow.get("Memo")==null ? "" : dataRow.get("Memo").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(40);
        	cell.setCellValue(dataRow.get("ResultRank")==null ? "" : dataRow.get("ResultRank").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(41);
        	cell.setCellValue(dataRow.get("Ldpe")==null ? "" : dataRow.get("Ldpe").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(42);
        	cell.setCellValue(dataRow.get("Eps")==null ? "" : dataRow.get("Eps").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(43);
        	cell.setCellValue(dataRow.get("Epe")==null ? "" : dataRow.get("Epe").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(44);
        	cell.setCellValue(dataRow.get("Pet")==null ? "" : dataRow.get("Pet").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(45);
        	cell.setCellValue(dataRow.get("Pp")==null ? "" : dataRow.get("Pp").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(46);
        	cell.setCellValue(dataRow.get("Pe")==null ? "" : dataRow.get("Pe").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(47);
        	cell.setCellValue(dataRow.get("Complex")==null ? "" : dataRow.get("Complex").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(48);
        	cell.setCellValue(dataRow.get("PlasticWeight")==null ? "" : dataRow.get("PlasticWeight").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(49);
        	cell.setCellValue(dataRow.get("CusFirstDt1")==null ? "" : dataRow.get("CusFirstDt1").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(50);
        	cell.setCellValue(dataRow.get("EcoAsCode")==null ? "" : dataRow.get("EcoAsCode").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(51);
        	cell.setCellValue(dataRow.get("EcoAsDtm")==null ? "" : dataRow.get("EcoAsDtm").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(52);
        	cell.setCellValue(dataRow.get("NetWt")==null ? "" : dataRow.get("NetWt").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(53);
        	cell.setCellValue(dataRow.get("RoHsReport")==null ? "" : dataRow.get("RoHsReport").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(54);
        	cell.setCellValue(dataRow.get("RoHsModel")==null ? "" : dataRow.get("RoHsModel").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(55);
        	cell.setCellValue(dataRow.get("AllSize")==null ? "" : dataRow.get("AllSize").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(56);
        	cell.setCellValue(dataRow.get("Weight")==null ? "" : dataRow.get("Weight").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(57);
        	cell.setCellValue(dataRow.get("Volume")==null ? "" : dataRow.get("Volume").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(58);
        	cell.setCellValue(dataRow.get("FileCnt")==null ? "" : dataRow.get("FileCnt").toString());
        	cell.setCellStyle(style);
		} catch (Exception e) {
			throw new RuntimeException("JSON streaming Exception", e);
		}
	}

	public void close(){
		try{
			workbook.write(response.getOutputStream());
			workbook.dispose();
		}catch (Exception e){
			response.setHeader("Set-Cookie", "fileDownload=false;path=/");
			response.setHeader("Cache-Control", "no-cache,no-store,must-revalidate");
			response.setHeader("Content-Type", "text/html;charset=utf-8");
			OutputStream out = null;
			try{
				out = response.getOutputStream();
				byte[] data = new String("fail Download.....").getBytes();
				out.write(data,0,data.length);
			}catch(Exception ex){
			}
		}finally{
			if(workbook != null){
				try{ workbook.close();}catch(Exception ex){}
			}
		}
	}
}