package com.edwards.biz.customsManagement;

import java.io.OutputStream;
import java.util.Map;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletResponse;

import org.apache.ibatis.session.ResultContext;
import org.apache.ibatis.session.ResultHandler;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.hssf.usermodel.HSSFDataFormat;
import org.apache.poi.xssf.streaming.*;
import org.apache.poi.xssf.usermodel.*;

public class BurberryExcel implements ResultHandler<Map<String,Object>> {
	private HttpServletResponse response;
	private SXSSFSheet sheet;
	private SXSSFWorkbook workbook;
	private boolean isStarted = false;

	XSSFCellStyle style   = null;
	XSSFCellStyle style1  = null;
	XSSFCellStyle style20 = null;
	XSSFCellStyle style22 = null;

	public BurberryExcel(HttpServletResponse response){
		this.response = response;
		workbook = new SXSSFWorkbook(100);
		sheet = workbook.createSheet("수입통합");
		sheet.setColumnWidth(0, 1500);
		sheet.setColumnWidth(1, 2000);
		sheet.setColumnWidth(2, 4500);
		sheet.setColumnWidth(3, 4500);
		sheet.setColumnWidth(4, 4500);
		sheet.setColumnWidth(5, 2500);
		sheet.setColumnWidth(6, 2500);
		sheet.setColumnWidth(7, 2500);
		sheet.setColumnWidth(8, 2500);
		sheet.setColumnWidth(9, 4500);
		sheet.setColumnWidth(10, 4500);
		sheet.setColumnWidth(11, 4500);
		sheet.setColumnWidth(12, 3000);
		sheet.setColumnWidth(13, 2000);
		sheet.setColumnWidth(14, 2000);
		sheet.setColumnWidth(15, 4000);
		sheet.setColumnWidth(16, 2000);
		sheet.setColumnWidth(17, 2000);
		sheet.setColumnWidth(18, 2500);
		sheet.setColumnWidth(19, 4000);
		sheet.setColumnWidth(20, 3500);
		sheet.setColumnWidth(21, 3000);
		sheet.setColumnWidth(22, 3000);
		sheet.setColumnWidth(23, 3000);
		sheet.setColumnWidth(24, 3000);
		sheet.setColumnWidth(25, 3000);
		sheet.setColumnWidth(26, 3000);
		sheet.setColumnWidth(27, 2500);
		sheet.setColumnWidth(28, 2500);
		sheet.setColumnWidth(29, 2000);
		sheet.setColumnWidth(30, 3000);
		sheet.setColumnWidth(31, 1500);
		sheet.setColumnWidth(32, 1500);
		sheet.setColumnWidth(33, 3000);
		sheet.setColumnWidth(34, 2000);
		sheet.setColumnWidth(35, 2000);
		sheet.setColumnWidth(36, 3000);
		sheet.setColumnWidth(37, 3000);
		sheet.setColumnWidth(38, 3500);
		sheet.setColumnWidth(39, 2500);
		sheet.setColumnWidth(40, 5000);
		sheet.setColumnWidth(41, 5000);
		sheet.setColumnWidth(42, 5000);
		sheet.setColumnWidth(43, 5000);
		sheet.setColumnWidth(44, 5000);
		sheet.setColumnWidth(45, 5000);
		sheet.setColumnWidth(46, 5000);
	}

	@Override
	public void handleResult(ResultContext<? extends Map<String, Object>> result){
		try {
			if(!isStarted){
        		style   = (XSSFCellStyle) workbook.createCellStyle();
        		style1  = (XSSFCellStyle) workbook.createCellStyle();
        		style20 = (XSSFCellStyle) workbook.createCellStyle();
        		style22 = (XSSFCellStyle) workbook.createCellStyle();

        		style.setBorderBottom(BorderStyle.THIN);
            	style.setBorderLeft(BorderStyle.THIN);
            	style.setBorderRight(BorderStyle.THIN);
            	style.setBorderTop(BorderStyle.THIN);
        		style.setAlignment(HorizontalAlignment.CENTER);

        		style1.setBorderBottom(BorderStyle.THIN);
            	style1.setBorderLeft(BorderStyle.THIN);
            	style1.setBorderRight(BorderStyle.THIN);
            	style1.setBorderTop(BorderStyle.THIN);

        		style20.setDataFormat(HSSFDataFormat.getBuiltinFormat("#,##0"));
        		style20.setBorderBottom(BorderStyle.THIN);
            	style20.setBorderLeft(BorderStyle.THIN);
            	style20.setBorderRight(BorderStyle.THIN);
            	style20.setBorderTop(BorderStyle.THIN);
        		style20.setAlignment(HorizontalAlignment.RIGHT);

        		style22.setDataFormat(HSSFDataFormat.getBuiltinFormat("#,##0.00"));
        		style22.setBorderBottom(BorderStyle.THIN);
        		style22.setBorderLeft(BorderStyle.THIN);
        		style22.setBorderRight(BorderStyle.THIN);
        		style22.setBorderTop(BorderStyle.THIN);
        		style22.setAlignment(HorizontalAlignment.RIGHT);

        		response.setHeader("Content-Disposition","attachment;filename=\""+URLEncoder.encode("수입통합.xlsx", "UTF-8")+"\"");
        		isStarted = true;
        		SXSSFRow row = sheet.createRow(0);
        		SXSSFCell cell = row.createCell(0);
        		cell.setCellValue("Status");
        		cell.setCellStyle(style);
        		cell = row.createCell(1);
        		cell.setCellValue("검사여부");
        		cell.setCellStyle(style);
        		cell = row.createCell(2);
        		cell.setCellValue("납세자상호");
        		cell.setCellStyle(style);
        		cell = row.createCell(3);
        		cell.setCellValue("B/L No.");
        		cell.setCellStyle(style);
        		cell = row.createCell(4);
        		cell.setCellValue("신고번호");
        		cell.setCellStyle(style);
        		cell = row.createCell(5);
        		cell.setCellValue("입항일");
        		cell.setCellStyle(style);
        		cell = row.createCell(6);
        		cell.setCellValue("반입일");
        		cell.setCellStyle(style);
        		cell = row.createCell(7);
        		cell.setCellValue("신고일");
        		cell.setCellStyle(style);
        		cell = row.createCell(8);
        		cell.setCellValue("수리일");
        		cell.setCellStyle(style);
        		cell = row.createCell(9);
        		cell.setCellValue("Ref No1");
        		cell.setCellStyle(style);
        		cell = row.createCell(10);
        		cell.setCellValue("거래품명");
        		cell.setCellStyle(style);
        		cell = row.createCell(11);
        		cell.setCellValue("무역거래처");
        		cell.setCellStyle(style);
        		cell = row.createCell(12);
        		cell.setCellValue("적출국");
        		cell.setCellStyle(style);
        		cell = row.createCell(13);
        		cell.setCellValue("세관");
        		cell.setCellStyle(style);
        		cell = row.createCell(14);
        		cell.setCellValue("양륙항");
        		cell.setCellStyle(style);
        		cell = row.createCell(15);
        		cell.setCellValue("장지장소");
        		cell.setCellStyle(style);
        		cell = row.createCell(16);
        		cell.setCellValue("인도조건");
        		cell.setCellStyle(style);
        		cell = row.createCell(17);
        		cell.setCellValue("포장수량");
        		cell.setCellStyle(style);
        		cell = row.createCell(18);
        		cell.setCellValue("중량");
        		cell.setCellStyle(style);
        		cell = row.createCell(19);
        		cell.setCellValue("Forwarder");
        		cell.setCellStyle(style);
        		cell = row.createCell(20);
        		cell.setCellValue("Invoice Amount");
        		cell.setCellStyle(style);
        		cell = row.createCell(21);
        		cell.setCellValue("총세액");
        		cell.setCellStyle(style);
        		cell = row.createCell(22);
        		cell.setCellValue("과세운임(원)");
        		cell.setCellStyle(style);
        		cell = row.createCell(23);
        		cell.setCellValue("CIF(원)");
        		cell.setCellStyle(style);
        		cell = row.createCell(24);
        		cell.setCellValue("관세");
        		cell.setCellStyle(style);
        		cell = row.createCell(25);
        		cell.setCellValue("부가세");
        		cell.setCellStyle(style);
        		cell = row.createCell(26);
        		cell.setCellValue("기타세");
        		cell.setCellStyle(style);
        		cell = row.createCell(27);
        		cell.setCellValue("가산금구분");
        		cell.setCellStyle(style);
        		cell = row.createCell(28);
        		cell.setCellValue("가산율");
        		cell.setCellStyle(style);
        		cell = row.createCell(29);
        		cell.setCellValue("가산금통화단위");
        		cell.setCellStyle(style);
        		cell = row.createCell(30);
        		cell.setCellValue("가산금원화");
        		cell.setCellStyle(style);
        		cell = row.createCell(31);
        		cell.setCellValue("란");
        		cell.setCellStyle(style);
        		cell = row.createCell(32);
        		cell.setCellValue("행");
        		cell.setCellStyle(style);
        		cell = row.createCell(33);
        		cell.setCellValue("자재코드");
        		cell.setCellStyle(style);
        		cell = row.createCell(34);
        		cell.setCellValue("수량");
        		cell.setCellStyle(style);
        		cell = row.createCell(35);
        		cell.setCellValue("단위");
        		cell.setCellStyle(style);
        		cell = row.createCell(36);
        		cell.setCellValue("단가");
        		cell.setCellStyle(style);
        		cell = row.createCell(37);
        		cell.setCellValue("금액");
        		cell.setCellStyle(style);
        		cell = row.createCell(38);
        		cell.setCellValue("Invoice No.");
        		cell.setCellStyle(style);
        		cell = row.createCell(39);
        		cell.setCellValue("Ship ID");
        		cell.setCellStyle(style);
        		cell = row.createCell(40);
        		cell.setCellValue("Ship Desc");
        		cell.setCellStyle(style);
        		cell = row.createCell(41);
        		cell.setCellValue("규격1");
        		cell.setCellStyle(style);
        		cell = row.createCell(42);
        		cell.setCellValue("규격2");
        		cell.setCellStyle(style);
        		cell = row.createCell(43);
        		cell.setCellValue("규격3");
        		cell.setCellStyle(style);
        		cell = row.createCell(44);
        		cell.setCellValue("성분1");
        		cell.setCellStyle(style);
        		cell = row.createCell(45);
        		cell.setCellValue("성분2");
        		cell.setCellStyle(style);
        		cell = row.createCell(46);
        		cell.setCellValue("성분3");
        		cell.setCellStyle(style);
        	}

        	Map<String, Object> dataRow = result.getResultObject();
        	Row row = sheet.createRow(result.getResultCount());
        	Cell cell = null;
        	cell = row.createCell(0);
        	cell.setCellValue(dataRow.get("Impo_receive_result")==null ? "" : dataRow.get("Impo_receive_result").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(1);
        	cell.setCellValue(dataRow.get("Impo_cs")==null ? "" : dataRow.get("Impo_cs").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(2);
        	cell.setCellValue(dataRow.get("Impo_napse_sangho")==null ? "" : dataRow.get("Impo_napse_sangho").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(3);
        	cell.setCellValue(dataRow.get("Impo_bl_no")==null ? "" : dataRow.get("Impo_bl_no").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(4);
        	cell.setCellValue(dataRow.get("Impo_singo_no")==null ? "" : dataRow.get("Impo_singo_no").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(5);
        	cell.setCellValue(dataRow.get("Impo_iphang_date")==null ? "" : dataRow.get("Impo_iphang_date").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(6);
        	cell.setCellValue(dataRow.get("Impo_banip_date")==null ? "" : dataRow.get("Impo_banip_date").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(7);
        	cell.setCellValue(dataRow.get("Impo_singo_date")==null ? "" : dataRow.get("Impo_singo_date").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(8);
        	cell.setCellValue(dataRow.get("Impo_Ok_date")==null ? "" : dataRow.get("Impo_Ok_date").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(9);
        	cell.setCellValue(dataRow.get("Impo_file_no1")==null ? "" : dataRow.get("Impo_file_no1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(10);
        	cell.setCellValue(dataRow.get("imlanGuraePum")==null ? "" : dataRow.get("imlanGuraePum").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(11);
        	cell.setCellValue(dataRow.get("Impo_gonggub_sangho")==null ? "" : dataRow.get("Impo_gonggub_sangho").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(12);
        	cell.setCellValue(dataRow.get("Impo_jukchl_name")==null ? "" : dataRow.get("Impo_jukchl_name").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(13);
        	cell.setCellValue(dataRow.get("segwanName")==null ? "" : dataRow.get("segwanName").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(14);
        	cell.setCellValue(dataRow.get("Impo_hanggu_name")==null ? "" : dataRow.get("Impo_hanggu_name").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(15);
        	cell.setCellValue(dataRow.get("Impo_jangch_name")==null ? "" : dataRow.get("Impo_jangch_name").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(16);
        	cell.setCellValue(dataRow.get("Impo_indo_jogun")==null ? "" : dataRow.get("Impo_indo_jogun").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(17);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_pojang_su").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_pojang_su").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(18);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_total_jung").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_total_jung").toString()));
        	cell.setCellStyle(style22);
        	cell = row.createCell(19);
        	cell.setCellValue(dataRow.get("Impo_Forwarder_sangho")==null ? "" : dataRow.get("Impo_Forwarder_sangho").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(20);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_Gyelje_Input").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_Gyelje_Input").toString()));
        	cell.setCellStyle(style22);
        	cell = row.createCell(21);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_total_tax").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_total_tax").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(22);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_fre_won").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_fre_won").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(23);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_cif_total_won").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_cif_total_won").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(24);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_gwan_tax").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_gwan_tax").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(25);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_vat_tax").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_vat_tax").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(26);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_etc_tax").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_etc_tax").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(27);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_plus_yul_gubun").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_plus_yul_gubun").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(28);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_plus_yul").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_plus_yul").toString()));
        	cell.setCellStyle(style22);
        	cell = row.createCell(29);
        	cell.setCellValue(dataRow.get("Impo_plus_money")==null ? "" : dataRow.get("Impo_plus_money").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(30);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_plus_won").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_plus_won").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(31);
        	cell.setCellValue(dataRow.get("Impum_lan")==null ? "" : dataRow.get("Impum_lan").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(32);
        	cell.setCellValue(dataRow.get("Impum_heang")==null ? "" : dataRow.get("Impum_heang").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(33);
        	cell.setCellValue(dataRow.get("Impum_jajae_code")==null ? "" : dataRow.get("Impum_jajae_code").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(34);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impum_su").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impum_su").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(35);
        	cell.setCellValue(dataRow.get("Impum_su_danwi")==null ? "" : dataRow.get("Impum_su_danwi").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(36);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impum_danga").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impum_danga").toString()));
        	cell.setCellStyle(style22);
        	cell = row.createCell(37);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impum_amt").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impum_amt").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(38);
        	cell.setCellValue(dataRow.get("Impum_ivno")==null ? "" : dataRow.get("Impum_ivno").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(39);
        	cell.setCellValue(dataRow.get("C31")==null ? "" : dataRow.get("C31").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(40);
        	cell.setCellValue(dataRow.get("IMPUM_KEYWD")==null ? "" : dataRow.get("IMPUM_KEYWD").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(41);
        	cell.setCellValue(dataRow.get("Impum_gukyk1")==null ? "" : dataRow.get("Impum_gukyk1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(42);
        	cell.setCellValue(dataRow.get("Impum_gukyk2")==null ? "" : dataRow.get("Impum_gukyk2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(43);
        	cell.setCellValue(dataRow.get("Impum_gukyk3")==null ? "" : dataRow.get("Impum_gukyk3").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(44);
        	cell.setCellValue(dataRow.get("Impum_sungbun1")==null ? "" : dataRow.get("Impum_sungbun1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(45);
        	cell.setCellValue(dataRow.get("Impum_sungbun2")==null ? "" : dataRow.get("Impum_sungbun2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(46);
        	cell.setCellValue(dataRow.get("Impum_sungbun3")==null ? "" : dataRow.get("Impum_sungbun3").toString());
        	cell.setCellStyle(style1);
		} catch (Exception e) {
			throw new RuntimeException("JSON streaming Exception", e);
		}
	}

	public void close(){
		try{
			workbook.write(response.getOutputStream());
			workbook.dispose();
		}catch (Exception e){
			response.setHeader("Set-Cookie", "fileDownload=false;path=/");
			response.setHeader("Cache-Control", "no-cache,no-store,must-revalidate");
			response.setHeader("Content-Type", "text/html;charset=utf-8");
			OutputStream out = null;
			try{
				out = response.getOutputStream();
				byte[] data = new String("fail Download.....").getBytes();
				out.write(data,0,data.length);
			}catch(Exception ex){
			}
		}finally{
			if(workbook != null){
				try{ workbook.close();}catch(Exception ex){}
			}
		}
	}
}