package com.edwards.biz.customsManagement;

import java.io.OutputStream;
import java.util.Map;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletResponse;

import org.apache.ibatis.session.ResultContext;
import org.apache.ibatis.session.ResultHandler;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.hssf.usermodel.HSSFDataFormat;
import org.apache.poi.xssf.streaming.*;
import org.apache.poi.xssf.usermodel.*;

public class PorscheItemExcel implements ResultHandler<Map<String,Object>> {
	private HttpServletResponse response;
	private SXSSFSheet sheet;
	private SXSSFWorkbook workbook;
	private boolean isStarted = false;

	XSSFCellStyle styleTop  = null;
	XSSFCellStyle style   	= null;
	XSSFCellStyle style1  	= null;
	XSSFCellStyle style20 	= null;
	XSSFCellStyle style22 	= null;

	public PorscheItemExcel(HttpServletResponse response){
		this.response = response;
		workbook = new SXSSFWorkbook(100);
		sheet = workbook.createSheet("Import");
		sheet.setColumnWidth(0, 2500);
		sheet.setColumnWidth(1, 2500);
		sheet.setColumnWidth(2, 6000);
		sheet.setColumnWidth(3, 6000);
		sheet.setColumnWidth(4, 4000);
		sheet.setColumnWidth(5, 4000);
		sheet.setColumnWidth(6, 4000);
		sheet.setColumnWidth(7, 4000);
		sheet.setColumnWidth(8, 6000);
		sheet.setColumnWidth(9, 6000);
		sheet.setColumnWidth(10, 5000);
		sheet.setColumnWidth(11, 3000);
		sheet.setColumnWidth(12, 3000);
		sheet.setColumnWidth(13, 3000);
		sheet.setColumnWidth(14, 3500);
		sheet.setColumnWidth(15, 3500);
		sheet.setColumnWidth(16, 4000);
		sheet.setColumnWidth(17, 3000);
		sheet.setColumnWidth(18, 3000);
		sheet.setColumnWidth(19, 3000);
		sheet.setColumnWidth(20, 4000);
		sheet.setColumnWidth(21, 3500);
		sheet.setColumnWidth(22, 3500);
		sheet.setColumnWidth(23, 3500);
		sheet.setColumnWidth(24, 3500);
		sheet.setColumnWidth(25, 3500);
		sheet.setColumnWidth(26, 3500);
		sheet.setColumnWidth(27, 3500);
		sheet.setColumnWidth(28, 2000);
		sheet.setColumnWidth(29, 2000);
		sheet.setColumnWidth(30, 3500);
		sheet.setColumnWidth(31, 2000);
		sheet.setColumnWidth(32, 2000);
		sheet.setColumnWidth(33, 3500);
		sheet.setColumnWidth(34, 3500);
		sheet.setColumnWidth(35, 5000);
		sheet.setColumnWidth(36, 5000);
		sheet.setColumnWidth(37, 5000);
		sheet.setColumnWidth(38, 5000);
		sheet.setColumnWidth(39, 5000);
		sheet.setColumnWidth(40, 5000);
	}

	@Override
	public void handleResult(ResultContext<? extends Map<String, Object>> result){
		try {
			if(!isStarted){
        		styleTop  = (XSSFCellStyle) workbook.createCellStyle();
        		style     = (XSSFCellStyle) workbook.createCellStyle();
        		style1    = (XSSFCellStyle) workbook.createCellStyle();
        		style20   = (XSSFCellStyle) workbook.createCellStyle();
        		style22   = (XSSFCellStyle) workbook.createCellStyle();

        		styleTop.setFillForegroundColor(new XSSFColor(new java.awt.Color(0, 234, 234)));
        		styleTop.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        		styleTop.setBorderBottom(BorderStyle.THIN);
        		styleTop.setBorderLeft(BorderStyle.THIN);
        		styleTop.setBorderRight(BorderStyle.THIN);
        		styleTop.setBorderTop(BorderStyle.THIN);
        		styleTop.setAlignment(HorizontalAlignment.CENTER);

        		style.setBorderBottom(BorderStyle.THIN);
            	style.setBorderLeft(BorderStyle.THIN);
            	style.setBorderRight(BorderStyle.THIN);
            	style.setBorderTop(BorderStyle.THIN);
        		style.setAlignment(HorizontalAlignment.CENTER);

        		style1.setBorderBottom(BorderStyle.THIN);
            	style1.setBorderLeft(BorderStyle.THIN);
            	style1.setBorderRight(BorderStyle.THIN);
            	style1.setBorderTop(BorderStyle.THIN);

        		style20.setDataFormat(HSSFDataFormat.getBuiltinFormat("#,##0"));
        		style20.setBorderBottom(BorderStyle.THIN);
            	style20.setBorderLeft(BorderStyle.THIN);
            	style20.setBorderRight(BorderStyle.THIN);
            	style20.setBorderTop(BorderStyle.THIN);
        		style20.setAlignment(HorizontalAlignment.RIGHT);

        		style22.setDataFormat(HSSFDataFormat.getBuiltinFormat("#,##0.00"));
        		style22.setBorderBottom(BorderStyle.THIN);
        		style22.setBorderLeft(BorderStyle.THIN);
        		style22.setBorderRight(BorderStyle.THIN);
        		style22.setBorderTop(BorderStyle.THIN);
        		style22.setAlignment(HorizontalAlignment.RIGHT);

        		response.setHeader("Content-Disposition","attachment;filename=\""+URLEncoder.encode("Import.xlsx", "UTF-8")+"\"");
        		isStarted = true;
        		SXSSFRow row = sheet.createRow(0);
        		SXSSFCell cell = row.createCell(0);
        		cell.setCellValue("Status");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(1);
        		cell.setCellValue("C/S Y/N");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(2);
        		cell.setCellValue("B/L No");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(3);
        		cell.setCellValue("Declaration No");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(4);
        		cell.setCellValue("D. Arrival");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(5);
        		cell.setCellValue("D. Warehousing");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(6);
        		cell.setCellValue("D. Declaration");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(7);
        		cell.setCellValue("D. Acceptance");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(8);
        		cell.setCellValue("VIN No");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(9);
        		cell.setCellValue("Description");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(10);
        		cell.setCellValue("Supplier");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(11);
        		cell.setCellValue("Currency unit");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(12);
        		cell.setCellValue("Transaction Classification");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(13);
        		cell.setCellValue("Country of Loading");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(14);
        		cell.setCellValue("Customshouse");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(15);
        		cell.setCellValue("Port of discharge");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(16);
        		cell.setCellValue("Warehousing site");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(17);
        		cell.setCellValue("Delivery conditions");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(18);
        		cell.setCellValue("Package");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(19);
        		cell.setCellValue("Weight");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(20);
        		cell.setCellValue("Forwarder");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(21);
        		cell.setCellValue("Invoice Amount");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(22);
        		cell.setCellValue("Total Tax");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(23);
        		cell.setCellValue("Taxable fare(￦)");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(24);
        		cell.setCellValue("CIF(￦)");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(25);
        		cell.setCellValue("Customs duties");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(26);
        		cell.setCellValue("VAT");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(27);
        		cell.setCellValue("Other taxes");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(28);
        		cell.setCellValue("Line");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(29);
        		cell.setCellValue("Model");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(30);
        		cell.setCellValue("Material Code");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(31);
        		cell.setCellValue("Quantity");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(32);
        		cell.setCellValue("Unit");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(33);
        		cell.setCellValue("Unit Price");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(34);
        		cell.setCellValue("Value");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(35);
        		cell.setCellValue("Standard1");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(36);
        		cell.setCellValue("Standard2");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(37);
        		cell.setCellValue("Standard3");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(38);
        		cell.setCellValue("Ingredient1");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(39);
        		cell.setCellValue("Ingredient2");
        		cell.setCellStyle(styleTop);
        		cell = row.createCell(40);
        		cell.setCellValue("Ingredient3");
        		cell.setCellStyle(styleTop);
        	}

        	Map<String, Object> dataRow = result.getResultObject();
        	Row row = sheet.createRow(result.getResultCount());
        	Cell cell = null;
        	cell = row.createCell(0);
        	cell.setCellValue(dataRow.get("Impo_receive_result")==null ? "" : dataRow.get("Impo_receive_result").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(1);
        	cell.setCellValue(dataRow.get("Impo_cs")==null ? "" : dataRow.get("Impo_cs").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(2);
        	cell.setCellValue(dataRow.get("Impo_bl_no")==null ? "" : dataRow.get("Impo_bl_no").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(3);
        	cell.setCellValue(dataRow.get("Impo_singo_no")==null ? "" : dataRow.get("Impo_singo_no").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(4);
        	cell.setCellValue(dataRow.get("Impo_iphang_date")==null ? "" : dataRow.get("Impo_iphang_date").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(5);
        	cell.setCellValue(dataRow.get("Impo_banip_date")==null ? "" : dataRow.get("Impo_banip_date").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(6);
        	cell.setCellValue(dataRow.get("Impo_singo_date")==null ? "" : dataRow.get("Impo_singo_date").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(7);
        	cell.setCellValue(dataRow.get("Impo_Ok_date")==null ? "" : dataRow.get("Impo_Ok_date").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(8);
        	cell.setCellValue(dataRow.get("Impo_file_no1")==null ? "" : dataRow.get("Impo_file_no1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(9);
        	cell.setCellValue(dataRow.get("imlanGuraePum")==null ? "" : dataRow.get("imlanGuraePum").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(10);
        	cell.setCellValue(dataRow.get("Impo_gonggub_sangho")==null ? "" : dataRow.get("Impo_gonggub_sangho").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(11);
        	cell.setCellValue(dataRow.get("impo_gyelje_money")==null ? "" : dataRow.get("impo_gyelje_money").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(12);
        	cell.setCellValue(dataRow.get("impo_gele_gubun")==null ? "" : dataRow.get("impo_gele_gubun").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(13);
        	cell.setCellValue(dataRow.get("Impo_jukchl_name")==null ? "" : dataRow.get("Impo_jukchl_name").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(14);
        	cell.setCellValue(dataRow.get("segwanName")==null ? "" : dataRow.get("segwanName").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(15);
        	cell.setCellValue(dataRow.get("Impo_hanggu_name")==null ? "" : dataRow.get("Impo_hanggu_name").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(16);
        	cell.setCellValue(dataRow.get("Impo_jangch_name")==null ? "" : dataRow.get("Impo_jangch_name").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(17);
        	cell.setCellValue(dataRow.get("Impo_indo_jogun")==null ? "" : dataRow.get("Impo_indo_jogun").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(18);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_pojang_su").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_pojang_su").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(19);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_total_jung").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_total_jung").toString()));
        	cell.setCellStyle(style22);
        	cell = row.createCell(20);
        	cell.setCellValue(dataRow.get("Impo_Forwarder_sangho")==null ? "" : dataRow.get("Impo_Forwarder_sangho").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(21);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_Gyelje_Input").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_Gyelje_Input").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(22);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_total_tax").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_total_tax").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(23);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_fre_won").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_fre_won").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(24);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_cif_total_won").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_cif_total_won").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(25);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_gwan_tax").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_gwan_tax").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(26);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_vat_tax").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_vat_tax").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(27);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impo_etc_tax").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impo_etc_tax").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(28);
        	cell.setCellValue(dataRow.get("Impum_lan")==null ? "" : dataRow.get("Impum_lan").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(29);
        	cell.setCellValue(dataRow.get("Impum_heang")==null ? "" : dataRow.get("Impum_heang").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(30);
        	cell.setCellValue(dataRow.get("Impum_jajae_code")==null ? "" : dataRow.get("Impum_jajae_code").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(31);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impum_su").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impum_su").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(32);
        	cell.setCellValue(dataRow.get("Impum_su_danwi")==null ? "" : dataRow.get("Impum_su_danwi").toString());
        	cell.setCellStyle(style);
        	cell = row.createCell(33);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impum_danga").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impum_danga").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(34);
        	cell.setCellValue(Double.parseDouble(dataRow.get("Impum_amt").toString())==0 ? 0 : Double.parseDouble(dataRow.get("Impum_amt").toString()));
        	cell.setCellStyle(style20);
        	cell = row.createCell(35);
        	cell.setCellValue(dataRow.get("Impum_gukyk1")==null ? "" : dataRow.get("Impum_gukyk1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(36);
        	cell.setCellValue(dataRow.get("Impum_gukyk2")==null ? "" : dataRow.get("Impum_gukyk2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(37);
        	cell.setCellValue(dataRow.get("Impum_gukyk3")==null ? "" : dataRow.get("Impum_gukyk3").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(38);
        	cell.setCellValue(dataRow.get("Impum_sungbun1")==null ? "" : dataRow.get("Impum_sungbun1").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(39);
        	cell.setCellValue(dataRow.get("Impum_sungbun2")==null ? "" : dataRow.get("Impum_sungbun2").toString());
        	cell.setCellStyle(style1);
        	cell = row.createCell(40);
        	cell.setCellValue(dataRow.get("Impum_sungbun3")==null ? "" : dataRow.get("Impum_sungbun3").toString());
        	cell.setCellStyle(style1);
		} catch (Exception e) {
			throw new RuntimeException("JSON streaming Exception", e);
		}
	}

	public void close(){
		try{
			workbook.write(response.getOutputStream());
			workbook.dispose();
		}catch (Exception e){
			response.setHeader("Set-Cookie", "fileDownload=false;path=/");
			response.setHeader("Cache-Control", "no-cache,no-store,must-revalidate");
			response.setHeader("Content-Type", "text/html;charset=utf-8");
			OutputStream out = null;
			try{
				out = response.getOutputStream();
				byte[] data = new String("fail Download.....").getBytes();
				out.write(data,0,data.length);
			}catch(Exception ex){
			}
		}finally{
			if(workbook != null){
				try{ workbook.close();}catch(Exception ex){}
			}
		}
	}
}